### ISSUE TITLE
Report minimal python version in README

### ISSUE THREAD

**Issue by Manu343726** [johnmcfarlane/unformat#5]
I've followed your example and unformat fails with the following backtrace:

```
python3 $HOME/Documentos/unformat --root . "app/**/*.h" "app/**/*.cpp" 
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/manuel-sanchez/Documentos/unformat/__main__.py", line 85, in <module>
    main(args, pool)
  File "/home/manuel-sanchez/Documentos/unformat/__main__.py", line 47, in main
    source_filenames = gather_source_filenames(args.examples)
  File "/home/manuel-sanchez/Documentos/unformat/__main__.py", line 14, in gather_source_filenames
    globs = [glob(example, recursive=True) for example in examples]
  File "/home/manuel-sanchez/Documentos/unformat/__main__.py", line 14, in <listcomp>
    globs = [glob(example, recursive=True) for example in examples]
TypeError: glob() got an unexpected keyword argument 'recursive'
```

It seems that support of recursive globs [was added in python 3.5](https://docs.python.org/3.5/library/glob.html?highlight=recursive#glob.glob), which means `recursive` keyword is not available for any python less than 3.5 (Mine was 3.4.3).

**Comment by johnmcfarlane** [comment]
Thanks. I've added a note to the README.md for now that only Python 3.5 is confirmed.

**Comment by johnmcfarlane** [comment]
Since #10 you should be able to run with Python 3.4 but since I haven't tested this works, I'm keeping the reference to 3.5 in the *README.md*. If you find that the exception is gone, I'll revise that. Cheers, John

**Comment by Manu343726** [comment]
I will try to check it on 3.4 in a couple of days. Thanks.
